# Generated by Django 6.0.5 on 2026-05-25 18:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
        ('ingestion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmissionFactor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('substance', models.CharField(max_length=100)),
                ('scope', models.CharField(choices=[('SCOPE_1', 'Scope 1'), ('SCOPE_2', 'Scope 2'), ('SCOPE_3', 'Scope 3')], max_length=10)),
                ('factor_value', models.DecimalField(decimal_places=6, help_text='kg CO2e per unit', max_digits=12)),
                ('unit', models.CharField(max_length=20)),
                ('source', models.CharField(max_length=100)),
                ('version', models.CharField(max_length=20)),
                ('valid_from', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='NormalizedRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scope', models.CharField(choices=[('SCOPE_1', 'Scope 1'), ('SCOPE_2', 'Scope 2'), ('SCOPE_3', 'Scope 3')], max_length=10)),
                ('category', models.CharField(blank=True, max_length=100)),
                ('source_type', models.CharField(max_length=50)),
                ('reporting_date', models.DateField()),
                ('activity_type', models.CharField(max_length=100)),
                ('original_quantity', models.DecimalField(blank=True, decimal_places=4, max_digits=15, null=True)),
                ('original_unit', models.CharField(blank=True, max_length=20)),
                ('normalized_quantity', models.DecimalField(decimal_places=4, max_digits=15)),
                ('normalized_unit', models.CharField(max_length=20)),
                ('calculated_emissions_kg', models.DecimalField(blank=True, decimal_places=4, max_digits=15, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending Review'), ('FLAGGED', 'Flagged'), ('APPROVED', 'Approved'), ('LOCKED', 'Locked')], default='PENDING', max_length=20)),
                ('anomaly_reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='normalized_records', to='clients.client')),
                ('emission_factor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='normalization.emissionfactor')),
                ('raw_record', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='normalized_record', to='ingestion.rawrecord')),
            ],
        ),
    ]
