# Generated by Django 6.0.5 on 2026-05-25 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('before_state', models.JSONField(help_text='Record state before edit')),
                ('after_state', models.JSONField(help_text='Record state after edit')),
                ('reason', models.TextField(blank=True)),
            ],
        ),
    ]
